---
title: nerdco.io
author: nerdco.io
email: support@nerdco.io
description: nerdco.io is a cardano stake pool with a mission
baseurl: "/"
url: nerdco.io
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
